import sqlite3
class Database():
    def __init__(self):
        # ...
        self._db = sqlite3.connect('database.db')
        # ...
    
    def addURL(self, url):
        # ...
        self._db.execute("INSERT INTO urls (url, date) VALUES (?, ?)", (url, self.currentDateEpoch))
        self._db.commit()
        # ...
    
